services:
  
  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:3000

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:16.6-alpine3.21
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}:5432

    volumes:
      - pg_data:/var/lib/postgres/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: always


volumes:
  pg_data:
