basePath: /api/v1
definitions:
  dto.HttpErr:
    properties:
      err:
        example: some error description
        type: string
    type: object
  dto.UserAuthResponse:
    properties:
      token:
        type: string
    type: object
  dto.UserLogin:
    properties:
      email:
        example: yoyoyo@femail.ru
        type: string
      password:
        example: qwerty234sraiekvaroisehw{}$
        type: string
    required:
    - email
    - password
    type: object
  dto.UserRegister:
    properties:
      email:
        example: yoyoyo@femail.ru
        format: email
        type: string
      name:
        example: msa
        maxLength: 16
        type: string
      password:
        example: qwerty123_AOISROKT(:#*L(*))
        type: string
    required:
    - name
    type: object
host: localhost:3000
info:
  contact: {}
  title: Golang clean-arch Web Template
  version: "1.0"
paths:
  /user/sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: Logins existed user and returns access token
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/dto.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserAuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpErr'
      summary: login existed user
      tags:
      - users
  /user/sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registers new user and returns access token
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegister'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserAuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpErr'
      summary: register new user
      tags:
      - users
swagger: "2.0"
